name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *' # Her gün gece 12'de çalışır
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TOTAL_CODE_TIME: true
          SHOW_LANGUAGE: true
          SHOW_OS: false
          SHOW_PROJECTS: true
